# Config principal de nginx para runtime no-root:
#  - pid en /tmp (permite ejecutar nginx como appuser sin permisos sobre /var/run)
#  - sin la directiva `user` (con master no-root se ignoraría con warning)
worker_processes  auto;

pid  /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    include /etc/nginx/conf.d/*.conf;
}